#ifndef DIELECTRIC_FUNCTIONH
#define DIELECTRIC_FUNCTIONH

void contract_three_centre_overlap(double*, double, double*, FERMI*, PAIR_TRAN*, TRIPLE_TRAN*, CRYSTAL*, ATOM*, SHELL*, ATOM*, SHELL*, SYMMETRY*, REAL_LATTICE*, JOB_PARAM*, FILES);

void three_centre_coulomb_exchange(ComplexMatrix*, ComplexMatrix*, ComplexMatrix*, double*, FERMI*, PAIR_TRAN*, TRIPLE_TRAN*, CRYSTAL*, ATOM*, SHELL*, SYMMETRY*, REAL_LATTICE*, JOB_PARAM*, FILES);

void epsilon_q(ComplexMatrix*, FERMI*, PAIR_TRAN*, ATOM_TRAN*, ATOM*, SHELL*, GAUSSIAN*, ATOM*, SHELL*, GAUSSIAN*, CRYSTAL*, SYMMETRY*, REAL_LATTICE*, REAL_LATTICE_TABLES*, RECIPROCAL_LATTICE*, JOB_PARAM*, FILES);

void epsilon_molecule(ComplexMatrix*, FERMI*, PAIR_TRAN*, ATOM_TRAN*, ATOM*, SHELL*, GAUSSIAN*, ATOM*, SHELL*, GAUSSIAN*, CRYSTAL*, SYMMETRY*, REAL_LATTICE*, REAL_LATTICE_TABLES*, RECIPROCAL_LATTICE*, JOB_PARAM*, FILES);

#endif
