//#ifndef INPUTJOBH
//#define INPUTJOBH

int startjob(ATOM*, ATOM*, ATOM_TRAN*, SHELL*, GAUSSIAN*, SHELL*, GAUSSIAN*, CRYSTAL*, SYMMETRY*, REAL_LATTICE*, REAL_LATTICE_TABLES*, RECIPROCAL_LATTICE*G, JOB_PARAM*, FILES);

void fermi_default(FERMI*, CRYSTAL*, ATOM*, JOB_PARAM*, FILES);

//#endif


