
void integrals_crystal_ija(int, TRIPLE_TRAN*, int*, Complex*, REAL_LATTICE*, Q_LATTICE*, RECIPROCAL_LATTICE*, ATOM*, SHELL*, GAUSSIAN*, ATOM*, SHELL*, GAUSSIAN*, CRYSTAL*, JOB_PARAM*, FILES);
//void three_centre_coulomb1_reversed2_crystal_test1(int, TRIPLE_TRAN*, int*, Complex*, REAL_LATTICE*, Q_LATTICE*, RECIPROCAL_LATTICE*, ATOM*, SHELL*, GAUSSIAN*, ATOM*, SHELL*, GAUSSIAN*, CRYSTAL*, JOB_PARAM*, FILES);

void three_centre_coulomb1_reversed2_crystal_test2(INTEGRAL_LIST_COMPLEX*, int, TRIPLE_TRAN*, int*, Complex*, REAL_LATTICE*, Q_LATTICE*, RECIPROCAL_LATTICE*, ATOM*, SHELL*, GAUSSIAN*, ATOM*, SHELL*, GAUSSIAN*, CRYSTAL*, JOB_PARAM*, FILES);

