
void optical_spectrum_crystal2(FERMI*, ATOM*, ATOM_TRAN*_p, int*, int*, int [][2], SHELL*, GAUSSIAN*, ATOM*, SHELL*, GAUSSIAN*, CRYSTAL*, SYMMETRY*, REAL_LATTICE*, REAL_LATTICE_TABLES*, RECIPROCAL_LATTICE*, JOB_PARAM*, FILES);

